"""Constants for the FinTS Auto-Pay integration."""
DOMAIN = "fints_autopay"
CONF_SENSOR = "sensor"
CONF_NOTIFY = "notify"
CONF_TODO = "todo"
CONF_BLZ = "blz"
CONF_USERNAME = "username"
CONF_PIN = "pin"
CONF_ENDPOINT = "endpoint"
CONF_TARGET_IBAN = "target_iban"
CONF_RECIPIENT_NAME = "recipient_name"
